// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTKyQXEXiJz1pReG9Fbc0DDy1lD-7XEM',
    appId: '1:1071382237838:web:f8578d8614922640ee6fdf',
    messagingSenderId: '1071382237838',
    projectId: 'cloud-login-7f984',
    authDomain: 'cloud-login-7f984.firebaseapp.com',
    storageBucket: 'cloud-login-7f984.appspot.com',
    measurementId: 'G-K9YNM2Q929',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANrt2jrLbfKGhD55ZyCJ8xuLE_htP0wXM',
    appId: '1:1071382237838:android:0d31884fddd6fa4bee6fdf',
    messagingSenderId: '1071382237838',
    projectId: 'cloud-login-7f984',
    storageBucket: 'cloud-login-7f984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9HsHRsqhBqWSGNeyt49VMgvyEZ1xCOHw',
    appId: '1:1071382237838:ios:d8df89ab7193ba40ee6fdf',
    messagingSenderId: '1071382237838',
    projectId: 'cloud-login-7f984',
    storageBucket: 'cloud-login-7f984.appspot.com',
    iosClientId: '1071382237838-h68a4r80saa158rm6sq1utdkrgts41sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9HsHRsqhBqWSGNeyt49VMgvyEZ1xCOHw',
    appId: '1:1071382237838:ios:d8df89ab7193ba40ee6fdf',
    messagingSenderId: '1071382237838',
    projectId: 'cloud-login-7f984',
    storageBucket: 'cloud-login-7f984.appspot.com',
    iosClientId: '1071382237838-h68a4r80saa158rm6sq1utdkrgts41sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudLogin',
  );
}
